package com.example.finappapirest.finances.interfaces.rest;

import com.example.finappapirest.finances.interfaces.rest.resources.request.credit.CreateOnePaymentRequest;
import com.example.finappapirest.finances.interfaces.rest.resources.request.credit.CreateQuotaCreditRequest;
import com.example.finappapirest.finances.interfaces.rest.resources.response.credit.OnePaymentCreditResponse;
import com.example.finappapirest.finances.interfaces.rest.resources.response.credit.QuotaCreditResponse;
import com.example.finappapirest.finances.interfaces.rest.resources.response.credit.CreditResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/v1/credits")
@Tag(name = "Credits", description = "Credits management")
public class CreditController {

    @GetMapping()
    @Operation(summary = "Get all credits", description = "Get all credits in the system")
    public ResponseEntity<List<CreditResponse>> getAllCredits() {
        return ResponseEntity.ok(List.of());
    }

    @GetMapping("/{creditId}")
    @Operation(summary = "Get credit by id", description = "Get credit by id in the system")
    public ResponseEntity<CreditResponse> getCredit(@PathVariable Long creditId) {
        return null;
    }

    @GetMapping("/{accountId}")
    @Operation(summary = "Get credits by account", description = "Get credits for an account by account id in the system")
    public ResponseEntity<List<CreditResponse>> getCreditsByAccount(@PathVariable Long accountId) {
        return ResponseEntity.ok(List.of());
    }


    @GetMapping("/{storeId}")
    @Operation(summary = "Get credits by store", description = "Get credits for a store by store id in the system")
    public ResponseEntity<List<CreditResponse>> getCreditsByStore(@PathVariable Long storeId) {
        return ResponseEntity.ok(List.of());
    }

    @PostMapping("/one-payment-credit/{accountId}")
    @Operation(summary = "Create credit", description = "Create a credit for an account in the system")
    public ResponseEntity<OnePaymentCreditResponse> createOnePaymentCredit(@PathVariable Long accountId, @RequestBody CreateOnePaymentRequest creditRequest) {
        return null;
    }

    @PostMapping("/quota-credit/{accountId}")
    @Operation(summary = "Create credit", description = "Create a credit for an account in the system")
    public ResponseEntity<QuotaCreditResponse> createQuotaCredit(@PathVariable Long accountId, @RequestBody CreateQuotaCreditRequest creditRequest) {
        return null;
    }

    @PostMapping("/one-payment-credit/preview")
    @Operation(summary = "Preview credit", description = "Preview credit and payment plan generated by the system")
    public ResponseEntity<OnePaymentCreditResponse> previewCredit(@RequestBody CreateOnePaymentRequest creditRequest) {
        return null;
    }
    @PostMapping("/quota-credit/preview")
    @Operation(summary = "Preview credit", description = "Preview credit and payment plan generated by the system")
    public ResponseEntity<QuotaCreditResponse> previewCredit(@RequestBody CreateQuotaCreditRequest creditRequest) {
        return null;
    }

    @PatchMapping("/change-status/{creditId}")
    @Operation(summary = "Change credit status", description = "Change credit status in the system")
    public String changeCreditStatus(@PathVariable Long creditId) {
        return "Credit status changed " + creditId;
    }
}
